version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "auction-created:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  api:
    container_name: api
    build: ./api
    ports:
      - 3333:3333
    volumes:
      - ./api:/api
    depends_on:
      - kafka
    environment:
      - PORT=3333
      - KAFKA_SERVERS=kafka:9092
      - KAFKA_TOPIC=auction-created
      - KAFKA_CLIENT_ID=api
  notification-service:
    container_name: notification-service
    build: ./notification-service
    volumes:
      - ./notification-service:/notification-service
    depends_on:
      - kafka
    environment:
      - KAFKA_CLIENT_ID=notification-service
      - KAFKA_SERVERS=kafka:9092
      - KAFKA_TOPIC=auction-created